### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by rben01** [c2d7fa/vscode-parchment-light#9]
Wondering if a dark version of this theme is in the works, or how I could help out with making one.

**Comment by c2d7fa** [comment]
Personally, I prefer light themes, so I don't really want to make this myself. But I added an open-source license so you can fork this project and implement it yourself if you want to.

If so, there are some brief instructions in the README on how to build the project. You'll want to look at the code in the `src/` directory; it's just a short Python script that generates the actual theme file (because I wanted to use [HSLuv](https://www.hsluv.org/) for the colors). Feel free to ask if you have problems getting it to work.

**Comment by c2d7fa** [comment]
I changed my mind on this, so there are now a couple of dark variants included in the theme :)
